const movieDatabase = [
    {"title": "The Shawshank Redemption", "year": 1994}, 
    {"title": "The Godfather", "year": 1972}, 
    {"title": "The Dark Knight", "year": 2008}, 
    {"title": "The Godfather: Part II", "year": 1974}, 
    {"title": "12 Angry Men", "year": 1957}, 
    {"title": "The Lord of the Rings: The Return of the King", "year": 2003}, 
    {"title": "Pulp Fiction", "year": 1994}, {"title": "Schindler's List", "year": 1993}, 
    {"title": "Inception", "year": 2010}, {"title": "Fight Club", "year": 1999}, 
    {"title": "The Lord of the Rings: The Fellowship of the Ring", "year": 2001}, 
    {"title": "Forrest Gump", "year": 1994}, 
    {"title": "Il buono, il brutto, il cattivo", "year": 1966}, 
    {"title": "The Lord of the Rings: The Two Towers", "year": 2002}, 
    {"title": "The Matrix", "year": 1999}, 
    {"title": "Goodfellas", "year": 1990}, 
    {"title": "Star Wars: Episode V - The Empire Strikes Back", "year": 1980}, 
    {"title": "One Flew Over the Cuckoo's Nest", "year": 1975}, 
    {"title": "Hamilton", "year": 2020}, 
    {"title": "Gisaengchung", "year": 2019}, 
    {"title": "Soorarai Pottru", "year": 2020}, 
    {"title": "Interstellar", "year": 2014}, 
    {"title": "Cidade de Deus", "year": 2002}, 
    {"title": "Sen to Chihiro no kamikakushi", "year": 2001}, 
    {"title": "Saving Private Ryan", "year": 1998}, 
    {"title": "The Green Mile", "year": 1999}, 
    {"title": "La vita bella", "year": 1997}, 
    {"title": "Se7en", "year": 1995}, 
    {"title": "The Silence of the Lambs", "year": 1991}, 
    {"title": "Star Wars", "year": 1977}, 
    {"title": "Seppuku", "year": 1962}, 
    {"title": "Shichinin no samurai", "year": 1954},
    {"title": "It's a Wonderful Life", "year": 1946}, 
    {"title": "Joker", "year": 2019}, 
    {"title": "Whiplash", "year": 2014}, 
    {"title": "The Intouchables", "year": 2011}, 
    {"title": "The Prestige", "year": 2006}, 
    {"title": "The Departed", "year": 2006}, 
    {"title": "The Pianist", "year": 2002}, 
    {"title": "Gladiator", "year": 2000}, 
    {"title": "American History X", "year": 1998}, 
    {"title": "The Usual Suspects", "year": 1995}, 
    {"title": "Lion", "year": 1994}, 
    {"title": "The Lion King", "year": 1994}, 
    {"title": "Terminator 2: Judgment Day", "year": 1991}, 
    {"title": "Nuovo Cinema Paradiso", "year": 1988}, 
    {"title": "Hotaru no haka", "year": 1988}, 
    {"title": "Back to the Future", "year": 1985}, 
    {"title": "Once Upon a Time in the West", "year": 1968}, 
    {"title": "Psycho", "year": 1960},
    {"title": "Casablanca", "year": 1942}, 
    {"title": "Modern Times", "year": 1936}, 
    {"title": "City Lights", "year": 1931}, 
    {"title": "Capharna", "year": 2018}, 
    {"title": "Ayla: The Daughter of War", "year": 2017}, 
    {"title": "Vikram Vedha", "year": 2017}, 
    {"title": "Kimi no na wa.", "year": 2016}, 
    {"title": "Dangal", "year": 2016}, 
    {"title": "Spider-Man: Into the Spider-Verse", "year": 2018}, 
    {"title": "Avengers: Endgame", "year": 2019}, 
    {"title": "Avengers: Infinity War", "year": 2018}, 
    {"title": "Coco", "year": 2017}, 
    {"title": "Django Unchained", "year": 2012}, 
    {"title": "The Dark Knight Rises", "year": 2012}, 
    {"title": "3 Idiots", "year": 2009}, 
    {"title": "Taare Zameen Par", "year": 2007}, 
    {"title": "WALLE", "year": 2008}, 
    {"title": "The Lives of Others", "year": 2006}, 
    {"title": "Oldeuboi", "year": 2003}, 
    {"title": "Memento", "year": 2000}, 
    {"title": "Mononoke-hime", "year": 1997}, 
    {"title": "Once Upon a Time in America", "year": 1984}, 
    {"title": "Raiders of the Lost Ark", "year": 1981}, 
    {"title": "The Shining", "year": 1980}, 
    {"title": "Apocalypse Now", "year": 1979}, 
    {"title": "Alien", "year": 1979}, 
    {"title": "Anand", "year": 1971}, 
    {"title": "Tengoku to jigoku", "year": 1963}, 
    {"title": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", "year": 1964}, 
    {"title": "Witness for the Prosecution", "year": 1957}, 
    {"title": "Paths of Glory", "year": 1957}, 
    {"title": "Rear Window", "year": 1954}, 
    {"title": "Sunset Blvd.", "year": 1950},
    {"title": "The Great Dictator", "year": 1940}, 
    {"title": "1917", "year": 2019}, 
    {"title": "Tumbbad", "year": 2018}, 
    {"title": "Andhadhun", "year": 2018}, 
    {"title": "Drishyam", "year": 2013}, 
    {"title": "Jagten", "year": 2012}, 
    {"title": "Jodaeiye Nader az Simin", "year": 2011}, 
    {"title": "Incendies", "year": 2010}, 
    {"title": "Miracle in cell NO.7", "year": 2019}, 
    {"title": "Babam ve Oglum", "year": 2005}, 
    {"title": "Inglourious Basterds", "year": 2009}, 
    {"title": "Eternal Sunshine of the Spotless Mind", "year": 2004}, 
    {"title": "Amlie", "year": 2001}, 
    {"title": "Snatch", "year": 2000}, 
    {"title": "Requiem for a Dream", "year": 2000}, 
    {"title": "American Beauty", "year": 1999}, 
    {"title": "Good Will Hunting", "year": 1997}, 
    {"title": "Bacheha-Ye aseman", "year": 1997}, 
    {"title": "Toy Story", "year": 1995}, 
    {"title": "Braveheart", "year": 1995}, 
    {"title": "Reservoir Dogs", "year": 1992}, 
    {"title": "Full Metal Jacket", "year": 1987}, 
    {"title": "Idi i smotri", "year": 1985}, 
    {"title": "Aliens", "year": 1986}, 
    {"title": "Amadeus", "year": 1984}, 
    {"title": "Scarface", "year": 1983}, 
    {"title": "Star Wars: Episode VI - Return of the Jedi", "year": 1983}, 
    {"title": "Das Boot", "year": 1981}, 
    {"title": "Taxi Driver", "year": 1976}, 
    {"title": "The Sting", "year": 1973}, 
    {"title": "A Clockwork Orange", "year": 1971}, 
    {"title": "2001: A Space Odyssey", "year": 1968}, 
    {"title": "Per qualche dollaro in pi", "year": 1965}, 
    {"title": "Lawrence of Arabia", "year": 1962}, 
    {"title": "The Apartment", "year": 1960}, 
    {"title": "North by Northwest", "year": 1959}, 
    {"title": "Vertigo", "year": 1958}, 
    {"title": "Singin' in the Rain", "year": 1952}, 
    {"title": "Ikiru", "year": 1952}, 
    {"title": "Ladri di biciclette", "year": 1948}, 
    {"title": "Double Indemnity", "year": 1944}, 
    {"title": "Citizen Kane", "year": 1941}, 
    {"title": "M - Eine Stadt sucht einen Murder", "year": 1931}, 
    {"title": "Metropolis", "year": 1927}, 
    {"title": "The Kid", "year": 1921}, 
    {"title": "Chhichhore", "year": 2019}, 
    {"title": "Uri: The Surgical Strike", "year": 2018}, 
    {"title": "K.G.F: Chapter 1", "year": 2018}, 
    {"title": "Green Book", "year": 2018}, 
    {"title": "Three Billboards Outside Ebbing, Missouri", "year": 2017}, 
    {"title": "Talvar", "year": 2015}, 
    {"title": "Baahubali 2: The Conclusion", "year": 2017}, 
    {"title": "Klaus", "year": 2019}, 
    {"title": "Drishyam", "year": 2015}, 
    {"title": "Queen", "year": 2013}, 
    {"title": "Mandariinid", "year": 2013}, 
    {"title": "Bhaag Milkha Bhaag", "year": 2013}, 
    {"title": "Gangs of Wasseypur", "year": 2012}, 
    {"title": "Udaan", "year": 2010}, 
    {"title": "Paan Singh Tomar", "year": 2012}, 
    {"title": "El secreto de sus ojos", "year": 2009}, 
    {"title": "Warrior", "year": 2011}, 
    {"title": "Shutter Island", "year": 2010}, 
    {"title": "Up", "year": 2009}, 
    {"title": "The Wolf of Wall Street", "year": 2013}, 
    {"title": "Chak De! India", "year": 2007}, 
    {"title": "There Will Be Blood", "year": 2007}, 
    {"title": "Pan's Labyrinth", "year": 2006}, 
    {"title": "Toy Story 3", "year": 2010}, 
    {"title": "V for Vendetta", "year": 2005}, 
    {"title": "Rang De Basanti", "year": 2006}, 
    {"title": "Black", "year": 2005}, 
    {"title": "Batman Begins", "year": 2005}, 
    {"title": "Swades: We, the People", "year": 2004},
    {"title": "Der Untergang", "year": 2004}, 
    {"title": "Hauru no ugoku shiro", "year": 2004}, 
    {"title": "A Beautiful Mind", "year": 2001}, 
    {"title": "Hera Pheri", "year": 2000}, 
    {"title": "Lock, Stock and Two Smoking Barrels", "year": 1998}, 
    {"title": "L.A. Confidential", "year": 1997}, 
    {"title": "Eskiya", "year": 1996}, 
    {"title": "Heat", "year": 1995}, 
    {"title": "Casino", "year": 1995}, 
    {"title": "Andaz Apna Apna", "year": 1994}, 
    {"title": "Unforgiven", "year": 1992}, 
    {"title": "Indiana Jones and the Last Crusade", "year": 1989}, 
    {"title": "Dom za vesanje", "year": 1988}, 
    {"title": "Tonari no Totoro", "year": 1988}, 
    {"title": "Die Hard", "year": 1988}, 
    {"title": "Ran", "year": 1985}, 
    {"title": "Raging Bull", "year": 1980}, 
    {"title": "Stalker", "year": 1979}, 
    {"title": "Hstsonaten", "year": 1978}, 
    {"title": "The Message", "year": 1976}, 
    {"title": "Sholay", "year": 1975}, 
    {"title": "Monty Python and the Holy Grail", "year": 1975}, 
    {"title": "The Great Escape", "year": 1963}, 
    {"title": "To Kill a Mockingbird", "year": 1962}, 
    {"title": "Yojinbo", "year": 1961}, 
    {"title": "Judgment at Nuremberg", "year": 1961}, 
    {"title": "Some Like It Hot", "year": 1959}, 
    {"title": "Smultronstllet", "year": 1957}, 
    {"title": "Det sjunde inseglet", "year": 1957}, 
    {"title": "Du rififi chez les hommes", "year": 1955}, 
    {"title": "Dial M for Murder", "year": 1954}, 
    {"title": "Turky monogatari", "year": 1953}, 
    {"title": "Rashmoon", "year": 1950}, 
    {"title": "All About Eve", "year": 1950}, 
    {"title": "The Treasure of the Sierra Madre", "year": 1948}, 
    {"title": "To Be or Not to Be", "year": 1942}, 
    {"title": "The Gold Rush", "year": 1925}, 
    {"title": "Sherlock Jr.", "year": 1924}, 
    {"title": "Portrait de la jeune fille en feu", "year": 2019}, 
    {"title": "Pink", "year": 2016}, 
    {"title": "Koe no katachi", "year": 2016}, 
    {"title": "Contratiempo", "year": 2016}, 
    {"title": "Ah-ga-ssi", "year": 2016}, 
    {"title": "Mommy", "year": 2014}, 
    {"title": "Haider", "year": 2014}, 
    {"title": "Logan", "year": 2017}, 
    {"title": "Room", "year": 2015}, 
    {"title": "Relatos salvajes", "year": 2014}, 
    {"title": "Soul", "year": 2020}, 
    {"title": "Kis Uykusu", "year": 2014}, 
    {"title": "PK", "year": 2014}, 
    {"title": "OMG: Oh My God!", "year": 2012}, 
    {"title": "The Grand Budapest Hotel", "year": 2014}, 
    {"title": "Gone Girl", "year": 2014}, 
    {"title": "Akami kodomo no Ame to Yuki", "year": 2012}, 
    {"title": "Hacksaw Ridge", "year": 2016}, 
    {"title": "Inside Out", "year": 2015}, 
    {"title": "Barfi!", "year": 2012}, 
    {"title": "12 Years a Slave", "year": 2013}, 
    {"title": "Rush", "year": 2013}, 
    {"title": "Ford v Ferrari", "year": 2019}, 
    {"title": "Spotlight", "year": 2015}, 
    {"title": "Song of the Sea", "year": 2014}, 
    {"title": "Kahaani", "year": 2012}, 
    {"title": "Zindagi Na Milegi Dobara", "year": 2011}, 
    {"title": "Prisoners", "year": 2013}, 
    {"title": "Mad Max: Fury Road", "year": 2015}, 
    {"title": "A Wednesday", "year": 2008}, 
    {"title": "Gran Torino", "year": 2008}, 
    {"title": "Harry Potter and the Deathly Hallows: Part 2", "year": 2011}, 
    {"title": "Okuribito", "year": 2008}, 
    {"title": "Hachi: A Dog's Tale", "year": 2009}, 
    {"title": "Mary and Max", "year": 2009}, 
    {"title": "How to Train Your Dragon", "year": 2010}, 
    {"title": "Into the Wild", "year": 2007}, 
    {"title": "No Country for Old Men", "year": 2007}, 
    {"title": "Lage Raho Munna Bhai", "year": 2006}, 
    {"title": "Million Dollar Baby", "year": 2004}, 
    {"title": "Hotel Rwanda", "year": 2004}, 
    {"title": "Taegukgi hwinalrimyeo", "year": 2004}, 
    {"title": "Before Sunset", "year": 2004}, 
    {"title": "Munna Bhai M.B.B.S.", "year": 2003}, 
    {"title": "Salinui chueok", "year": 2003}, 
    {"title": "Dil Chahta Hai", "year": 2001}, 
    {"title": "Kill Bill: Vol. 1", "year": 2003}, 
    {"title": "Finding Nemo", "year": 2003}, 
    {"title": "Catch Me If You Can", "year": 2002}, 
    {"title": "Amores perros", "year": 2000}, 
    {"title": "Monsters, Inc.", "year": 2001}, 
    {"title": "Shin seiki Evangelion Gekij-ban: Air/Magokoro wo, kimi ni", "year": 1997}, 
    {"title": "Lagaan: Once Upon a Time in India", "year": 2001}, 
    {"title": "The Sixth Sense", "year": 1999}, 
    {"title": "La leggenda del pianista sull'oceano", "year": 1998}, 
    {"title": "The Truman Show", "year": 1998}, 
    {"title": "Crna macka, beli macor", "year": 1998}, 
    {"title": "The Big Lebowski", "year": 1998}, 
    {"title": "Fa yeung nin wah", "year": 2000}, 
    {"title": "Trainspotting", "year": 1996}, 
    {"title": "Fargo", "year": 1996}, 
    {"title": "Underground", "year": 1995}, 
    {"title": "La haine", "year": 1995}, 
    {"title": "Dilwale Dulhania Le Jayenge", "year": 1995}, 
    {"title": "Before Sunrise", "year": 1995}, 
    {"title": "Trois couleurs: Rouge", "year": 1994}, 
    {"title": "Chung Hing sam lam", "year": 1994}, 
    {"title": "Jurassic Park", "year": 1993}, 
    {"title": "In the Name of the Father", "year": 1993}, 
    {"title": "Ba wang bie ji", "year": 1993}, 
    {"title": "De hufng denglong gaogao guue", "year": 1991}, 
    {"title": "Dead Poets Society", "year": 1989}, 
    {"title": "Stand by Me", "year": 1986}, 
    {"title": "Platoon", "year": 1986}, 
    {"title": "Paris, Texas", "year": 1984}, 
    {"title": "Kaze no tani no Naushika", "year": 1984}, 
    {"title": "The Thing", "year": 1982}, 
    {"title": "Pink Floyd: The Wall", "year": 1982}, 
    {"title": "Fitzcarraldo", "year": 1982}, 
    {"title": "Fanny och Alexander", "year": 1982}, 
    {"title": "Blade Runner", "year": 1982}, 
    {"title": "The Elephant Man", "year": 1980}, 
    {"title": "Life of Brian", "year": 1979}, 
    {"title": "The Deer Hunter", "year": 1978}, 
    {"title": "Rocky", "year": 1976}, 
    {"title": "Network", "year": 1976}, 
    {"title": "Barry Lyndon", "year": 1975}, 
    {"title": "Zerkalo", "year": 1975}, 
    {"title": "Chinatown", "year": 1974}, 
    {"title": "Paper Moon", "year": 1973}, 
    {"title": "Viskningar och rop", "year": 1972},
    {"title": "Solaris", "year": 1972}, 
    {"title": "Le samourae", "year": 1967}, 
    {"title": "Cool Hand Luke", "year": 1967}, 
    {"title": "Persona", "year": 1966}, 
    {"title": "Andrei Rublev", "year": 1966}, 
    {"title": "La battaglia di Algeri", "year": 1966}, 
    {"title": "El angel exterminador", "year": 1962}, 
    {"title": "What Ever Happened to Baby Jane?", "year": 1962}, 
    {"title": "Sanjuro", "year": 1962}, 
    {"title": "The Man Who Shot Liberty Valance", "year": 1962}, 
    {"title": "Ivanovo detstvo", "year": 1962}, 
    {"title": "Jungfrukellan", "year": 1960}, 
    {"title": "Inherit the Wind", "year": 1960}, 
    {"title": "Les quatre cents coups", "year": 1959}, 
    {"title": "Ben-Hur", "year": 1959}, 
    {"title": "Kakushi-toride no san-akunin", "year": 1958}, 
    {"title": "Le notti di Cabiria", "year": 1957}, 
    {"title": "Kumonosu-j", "year": 1957}, 
    {"title": "The Bridge on the River Kwai", "year": 1957}, 
    {"title": "On the Waterfront", "year": 1954}, 
    {"title": "Le salaire de la peur", "year": 1953}, 
    {"title": "Ace in the Hole", "year": 1951}, 
    {"title": "White Heat", "year": 1949}, 
    {"title": "The Third Man", "year": 1949}, 
    {"title": "The Red Shoes", "year": 1948}, 
    {"title": "The Shop Around the Corner", "year": 1940}, 
    {"title": "Rebecca", "year": 1940}, 
    {"title": "Mr. Smith Goes to Washington", "year": 1939}, 
    {"title": "Gone with the Wind", "year": 1939}, 
    {"title": "La Grande Illusion", "year": 1937}, 
    {"title": "It Happened One Night", "year": 1934}, 
    {"title": "La passion de Jeanne d'Arc", "year": 1928}, 
    {"title": "The Circus", "year": 1928}, 
    {"title": "Sunrise: A Song of Two Humans", "year": 1927}, 
    {"title": "The General", "year": 1926}, 
    {"title": "Das Cabinet des Dr. Caligari", "year": 1920}, 
    {"title": "Badhaai ho", "year": 2018}, 
    {"title": "Togo", "year": 2019}, 
    {"title": "Airlift", "year": 2016}, 
    {"title": "Bajrangi Bhaijaan", "year": 2015}, 
    {"title": "Baby", "year": 2015}, 
    {"title": "La La Land", "year": 2016}, 
    {"title": "Lion", "year": 2016}, 
    {"title": "The Martian", "year": 2015}, 
    {"title": "Zootopia", "year": 2016}, 
    {"title": "Behubali: The Beginning", "year": 2015}, 
    {"title": "Kaguyahime no monogatari", "year": 2013}, 
    {"title": "Wonder", "year": 2017}, 
    {"title": "Gully Boy", "year": 2019}, 
    {"title": "Special Chabbis", "year": 2013}, 
    {"title": "Short Term 12", "year": 2013}, 
    {"title": "Serbuan maut 2: Berandal", "year": 2014}, 
    {"title": "The Imitation Game", "year": 2014}, 
    {"title": "Guardians of the Galaxy", "year": 2014}, 
    {"title": "Blade Runner 2049", "year": 2017}, 
    {"title": "Her", "year": 2013}, 
    {"title": "Bohemian Rhapsody", "year": 2018}, 
    {"title": "The Revenant", "year": 2015}, 
    {"title": "The Perks of Being a Wallflower", "year": 2012}, 
    {"title": "Tropa de Elite 2: O Inimigo Agora Outro", "year": 2010}, 
    {"title": "The King's Speech", "year": 2010}, 
    {"title": "The Help", "year": 2011}, 
    {"title": "Deadpool", "year": 2016}, 
    {"title": "Darbareye Elly", "year": 2009}, 
    {"title": "Dev.D", "year": 2009}, 
    {"title": "Yip Man", "year": 2008}, 
    {"title": "My Name Is Khan", "year": 2010}, 
    {"title": "Nefes: Vatan Sagolsun", "year": 2009}, 
    {"title": "Slumdog Millionaire", "year": 2008}, 
    {"title": "Black Swan", "year": 2010}, 
    {"title": "Tropa de Elite", "year": 2007}, 
    {"title": "The Avengers", "year": 2012}, 
    {"title": "Persepolis", "year": 2007}, 
    {"title": "Dallas Buyers Club", "year": 2013}, 
    {"title": "The Pursuit of Happyness", "year": 2006}, 
    {"title": "Blood Diamond", "year": 2006}, 
    {"title": "The Bourne Ultimatum", "year": 2007}, 
    {"title": "Bin-jip", "year": 2004}, 
    {"title": "Sin City", "year": 2005}, 
    {"title": "Le scaphandre et le papillon", "year": 2007}, 
    {"title": "G.O.R.A.", "year": 2004}, 
    {"title": "Ratatouille", "year": 2007}, 
    {"title": "Casino Royale", "year": 2006}, 
    {"title": "Kill Bill: Vol. 2", "year": 2004}, 
    {"title": "Vozvrashchenie", "year": 2003}, 
    {"title": "Bom Yeoareum Gaeul Gyeoul Geurigo Bom", "year": 2003}, 
    {"title": "Mar adentro", "year": 2014}, 
    {"title": "Cinderella Man", "year": 2005}, 
    {"title": "Kal Ho Naa Ho", "year": 2003}, 
    {"title": "Mou gaan dou", "year": 2002}, 
    {"title": "Pirates of the Caribbean: The Curse of the Black Pearl", "year": 2003}, 
    {"title": "Big Fish", "year": 2003}, 
    {"title": "The Incredibles", "year": 2004}, 
    {"title": "Yeopgijeogin geunyeo", "year": 2001}, 
    {"title": "Dogville", "year": 2003}, 
    {"title": "Vizontele", "year": 2001}, 
    {"title": "Donnie Darko", "year": 2001}, 
    {"title": "Magnolia", "year": 1999}, 
    {"title": "Dancer in the Dark", "year": 2000}, 
    {"title": "The Straight Story", "year": 1999}, 
    {"title": "Pfekuto bur", "year": 1997}, 
    {"title": "Festen", "year": 1998}, 
    {"title": "Central do Brasil", "year": 1998}, 
    {"title": "The Iron Giant", "year": 1999}, 
    {"title": "Knockin' on Heaven's Door", "year": 1997}, 
    {"title": "Sling Blade", "year": 1996}, 
    {"title": "Secrets & Lies", "year": 1996}, 
    {"title": "Twelve Monkeys", "year": 1995}, 
    {"title": "Kkaku Kidtai", "year": 1995}, 
    {"title": "The Nightmare Before Christmas", "year": 1993}, 
    {"title": "Groundhog Day", "year": 1993}, 
    {"title": "Bound by Honor", "year": 1993}, 
    {"title": "Scent of a Woman", "year": 1992}, 
    {"title": "Aladdin", "year": 1992}, 
    {"title": "JFK", "year": 1991}, 
    {"title": "Beauty and the Beast", "year": 1991}, 
    {"title": "Dances with Wolves", "year": 1990}, 
    {"title": "Do the Right Thing", "year": 1989}, 
    {"title": "Rain Man", "year": 1988}, 
    {"title": "Akira", "year": 1988}, 
    {"title": "The Princess Bride", "year": 1987}, 
    {"title": "Der Himmel ber Berlin", "year": 1987}, 
    {"title": "Au revoir les enfants", "year": 1987}, 
    {"title": "Tenk no shiro Rapyuta", "year": 1986}, 
    {"title": "The Terminator", "year": 1984}, 
    {"title": "Gandhi", "year": 1982}, 
    {"title": "Kagemusha", "year": 1980}, 
    {"title": "Being There", "year": 1979}, 
    {"title": "Annie Hall", "year": 1977}, 
    {"title": "Jaws", "year": 1975}, 
    {"title": "Dog Day Afternoon", "year": 1975}, 
    {"title": "Young Frankenstein", "year": 1974}, 
    {"title": "Papillon", "year": 1973}, 
    {"title": "The Exorcist", "year": 1973}, 
    {"title": "Sleuth", "year": 1972}, 
    {"title": "The Last Picture Show", "year": 1971}, 
    {"title": "Fiddler on the Roof", "year": 1971}, 
    {"title": "Il conformista", "year": 1970}, 
    {"title": "Butch Cassidy and the Sundance Kid", "year": 1969}, 
    {"title": "Rosemary's Baby", "year": 1968}, 
    {"title": "Planet of the Apes", "year": 1968}, 
    {"title": "The Graduate", "year": 1967}, 
    {"title": "Who's Afraid of Virginia Woolf?", "year": 1966}, 
    {"title": "The Sound of Music", "year": 1965}, 
    {"title": "Doctor Zhivago", "year": 1965}, 
    {"title": "Per un pugno di dollari", "year": 1964}, 
    {"title": "8", "year": 1963}, 
    {"title": "Vivre sa vie: Film en douze tableaux", "year": 1962}, 
    {"title": "The Hustler", "year": 1961}, 
    {"title": "La dolce vita", "year": 1960}, 
    {"title": "Rio Bravo", "year": 1959}, 
    {"title": "Anatomy of a Murder", "year": 1959}, 
    {"title": "Touch of Evil", "year": 1958}, 
    {"title": "Cat on a Hot Tin Roof", "year": 1958}, 
    {"title": "Sweet Smell of Success", "year": 1957}, 
    {"title": "The Killing", "year": 1956}, 
    {"title": "The Night of the Hunter", "year": 1955}, 
    {"title": "La Strada", "year": 1954}, 
    {"title": "Les diaboliques", "year": 1955}, 
    {"title": "Stalag 17", "year": 1953}, 
    {"title": "Roman Holiday", "year": 1953}, 
    {"title": "A Streetcar Named Desire", "year": 1951}, 
    {"title": "In a Lonely Place", "year": 1950}, 
    {"title": "Kind Hearts and Coronets", "year": 1949}, 
    {"title": "Rope", "year": 1948}, 
    {"title": "Out of the Past", "year": 1947}, 
    {"title": "Brief Encounter", "year": 1945}, 
    {"title": "Laura", "year": 1944}, 
    {"title": "The Best Years of Our Lives", "year": 1946}, 
    {"title": "Arsenic and Old Lace", "year": 1942}, 
    {"title": "The Maltese Falcon", "year": 1941}, 
    {"title": "The Grapes of Wrath", "year": 1940}, 
    {"title": "The Wizard of Oz", "year": 1939}, 
    {"title": "La rugle du jeu", "year": 1939}, 
    {"title": "The Thin Man", "year": 1934}, 
    {"title": "All Quiet on the Western Front", "year": 1930}, 
    {"title": "Bronenosets Potemkin", "year": 1925}, 
    {"title": "Knives Out", "year": 2019}, 
    {"title": "Dil Bechara", "year": 2020}, 
    {"title": "Manbiki kazoku", "year": 2018}, 
    {"title": "Marriage Story", "year": 2019}, 
    {"title": "Call Me by Your Name", "year": 2017}, 
    {"title": "I, Daniel Blake", "year": 2016}, 
    {"title": "Isle of Dogs", "year": 2018}, 
    {"title": "Hunt for the Wilderpeople", "year": 2016}, 
    {"title": "Captain Fantastic", "year": 2016}, 
    {"title": "Sing Street", "year": 2016}, 
    {"title": "Thor: Ragnarok", "year": 2017}, 
    {"title": "Nightcrawler", "year": 2014}, 
    {"title": "Jojo Rabbit", "year": 2019}, 
    {"title": "Arrival", "year": 2016}, 
    {"title": "Star Wars: Episode VII - The Force Awakens", "year": 2015}, 
    {"title": "Before Midnight", "year": 2013}, 
    {"title": "X-Men: Days of Future Past", "year": 2014}, 
    {"title": "Bir Zamanlar Anadolu'da", "year": 2011}, 
    {"title": "The Artist", "year": 2011}, 
    {"title": "Edge of Tomorrow", "year": 2014}, 
    {"title": "Amour", "year": 2012}, 
    {"title": "The Irishman", "year": 2019}, 
    {"title": "Un prophute", "year": 2009}, 
    {"title": "Moon", "year": 2009}, 
    {"title": "Lut den rutte komma in", "year": 2008}, 
    {"title": "District 9", "year": 2009}, 
    {"title": "The Wrestler", "year": 2008}, 
    {"title": "Jab We Met", "year": 2007}, 
    {"title": "Boyhood", "year": 2014}, 
    {"title": "4 luni, 3 saptamuni si 2 zile", "year": 2007}, 
    {"title": "Star Trek", "year": 2009}, 
    {"title": "In Bruges", "year": 2008}, 
    {"title": "The Man from Earth", "year": 2007}, 
    {"title": "Letters from Iwo Jima", "year": 2006}, 
    {"title": "The Fall", "year": 2006}, 
    {"title": "Life of Pi", "year": 2012}, 
    {"title": "Fantastic Mr. Fox", "year": 2009}, 
    {"title": "C.R.A.Z.Y.", "year": 2005}, 
    {"title": "Les choristes", "year": 2004}, 
    {"title": "Iron Man", "year": 2008}, 
    {"title": "Shaun of the Dead", "year": 2004}, 
    {"title": "Gegen die Wand", "year": 2004}, 
    {"title": "Mystic River", "year": 2003}, 
    {"title": "Harry Potter and the Prisoner of Azkaban", "year": 2004}, 
    {"title": "Ying xiong", "year": 2002}, 
    {"title": "Hable con ella", "year": 2002}, 
    {"title": "No Man's Land", "year": 2001}, 
    {"title": "Cowboy Bebop: Tengoku no tobira", "year": 2001}, 
    {"title": "The Bourne Identity", "year": 2002}, 
    {"title": "Nueve reinas", "year": 2000}, 
    {"title": "Children of Men", "year": 2006}, 
    {"title": "Almost Famous", "year": 2000}, 
    {"title": "Mulholland Dr.", "year": 2001}, 
    {"title": "Toy Story 2", "year": 1999}, 
    {"title": "Boogie Nights", "year": 1997}, 
    {"title": "Mimi wo sumaseba", "year": 1995}, 
    {"title": "Once Were Warriors", "year": 1994}, 
    {"title": "True Romance", "year": 1993}, 
    {"title": "Trois couleurs: Bleu", "year": 1993}, 
    {"title": "Jubua ninpubchu", "year": 1993}, 
    {"title": "Carlito's Way", "year": 1993}, 
    {"title": "Edward Scissorhands", "year": 1990}, 
    {"title": "My Left Foot: The Story of Christy Brown", "year": 1989}, 
    {"title": "Crimes and Misdemeanors", "year": 1989}, 
    {"title": "The Untouchables", "year": 1987}, 
    {"title": "Hannah and Her Sisters", "year": 1986}, 
    {"title": "Brazil", "year": 1985}, 
    {"title": "This Is Spinal Tap", "year": 1984}, 
    {"title": "A Christmas Story", "year": 1983}, 
    {"title": "The Blues Brothers", "year": 1980}, 
    {"title": "Manhattan", "year": 1979}, 
    {"title": "All That Jazz", "year": 1979}, 
    {"title": "Dawn of the Dead", "year": 1978}, 
    {"title": "All the President's Men", "year": 1976}, 
    {"title": "La montaua sagrada", "year": 1973}, 
    {"title": "Amarcord", "year": 1973}, 
    {"title": "Le charme discret de la bourgeoisie", "year": 1972}, 
    {"title": "Aguirre, der Zorn Gottes", "year": 1972}, 
    {"title": "Harold and Maude", "year": 1971}, 
    {"title": "Patton", "year": 1970}, 
    {"title": "The Wild Bunch", "year": 1969}, 
    {"title": "Night of the Living Dead", "year": 1968}, 
    {"title": "The Lion in Winter", "year": 1968}, 
    {"title": "In the Heat of the Night", "year": 1967}, 
    {"title": "Charade", "year": 1963}, 
    {"title": "The Manchurian Candidate", "year": 1962}, 
    {"title": "Spartacus", "year": 1960}, 
    {"title": "L'avventura", "year": 1960}, 
    {"title": "Hiroshima mon amour", "year": 1959}, 
    {"title": "The Ten Commandments", "year": 1956}, 
    {"title": "The Searchers", "year": 1956}, 
    {"title": "East of Eden", "year": 1955}, 
    {"title": "High Noon", "year": 1952}, 
    {"title": "Strangers on a Train", "year": 1951}, 
    {"title": "Harvey", "year": 1950}, 
    {"title": "Miracle on 34th Street", "year": 1947}, 
    {"title": "Notorious", "year": 1946}, 
    {"title": "The Big Sleep", "year": 1946}, 
    {"title": "The Lost Weekend", "year": 1945}, 
    {"title": "The Philadelphia Story", "year": 1940}, 
    {"title": "His Girl Friday", "year": 1940}, 
    {"title": "The Adventures of Robin Hood", "year": 1938}, 
    {"title": "A Night at the Opera", "year": 1935}, 
    {"title": "King Kong", "year": 1933}, 
    {"title": "Freaks", "year": 1932}, 
    {"title": "Nosferatu", "year": 1922}, 
    {"title": "The Gentlemen", "year": 2019}, 
    {"title": "Raazi", "year": 2018}, 
    {"title": "Sound of Metal", "year": 2019}, 
    {"title": "Forushande", "year": 2016}, 
    {"title": "Dunkirk", "year": 2017}, 
    {"title": "Perfetti sconosciuti", "year": 2016}, 
    {"title": "Hidden Figures", "year": 2016}, 
    {"title": "Paddington 2", "year": 2017}, 
    {"title": "Udta Punjab", "year": 2016}, 
    {"title": "Kubo and the Two Strings", "year": 2016}, 
    {"title": "M.S. Dhoni: The Untold Story", "year": 2016}, 
    {"title": "Manchester by the Sea", "year": 2016}, 
    {"title": "Under sandet", "year": 2015}, 
    {"title": "Rogue One", "year": 2016}, 
    {"title": "Captain America: Civil War", "year": 2016}, 
    {"title": "The Hateful Eight", "year": 2015}, 
    {"title": "Little Women", "year": 2019}, 
    {"title": "Loving Vincent", "year": 2017}, 
    {"title": "Pride", "year": 2014}, 
    {"title": "Le passu", "year": 2013}, 
    {"title": "La grande bellezza", "year": 2013}, 
    {"title": "The Lunchbox", "year": 2013}, 
    {"title": "Vicky Donor", "year": 2012}, 
    {"title": "Big Hero 6", "year": 2014}, 
    {"title": "About Time", "year": 2013}, 
    {"title": "English Vinglish", "year": 2012}, 
    {"title": "Kaze tachinu", "year": 2013}, 
    {"title": "Toy Story 4", "year": 2019}, 
    {"title": "La migliore offerta", "year": 2013}, 
    {"title": "Moonrise Kingdom", "year": 2012}, 
    {"title": "How to Train Your Dragon 2", "year": 2014}, 
    {"title": "The Big Short", "year": 2015}, 
    {"title": "Kokuhaku", "year": 2010}, 
    {"title": "Ang-ma-reul bo-at-da", "year": 2010}, 
    {"title": "The Girl with the Dragon Tattoo", "year": 2011}, 
    {"title": "Captain Phillips", "year": 2013}, 
    {"title": "Ajeossi", "year": 2010}, 
    {"title": "Straight Outta Compton", "year": 2015}, 
    {"title": "Madeo", "year": 2009}, 
    {"title": "Chugyeokja", "year": 2008}, 
    {"title": "The Hobbit: The Desolation of Smaug", "year": 2013}, 
    {"title": "Das weiue Band - Eine deutsche Kindergeschichte", "year": 2009}, {"title": "Mun som hatar kvinnor", "year": 2009}, {"title": "The Trial of the Chicago 7", "year": 2020}, {"title": "Druk", "year": 2020}, {"title": "The Fighter", "year": 2010}, {"title": "Taken", "year": 2008}, {"title": "The Boy in the Striped Pyjamas", "year": 2008}, {"title": "Once", "year": 2007}, {"title": "The Hobbit: An Unexpected Journey", "year": 2012}, {"title": "Auf der anderen Seite", "year": 2007}, {"title": "Atonement", "year": 2007}, {"title": "Drive", "year": 2011}, {"title": "American Gangster", "year": 2007}, {"title": "Avatar", "year": 2009}, {"title": "Mr. Nobody", "year": 2009}, {"title": "Apocalypto", "year": 2006}, {"title": "Little Miss Sunshine", "year": 2006}, {"title": "Hot Fuzz", "year": 2007}, {"title": "The Curious Case of Benjamin Button", "year": 2008}, {"title": "Veer-Zaara", "year": 2004}, {"title": "Adams \u00e6bler", "year": 2005}, {"title": "Pride & Prejudice", "year": 2005}, {"title": "The World's Fastest Indian", "year": 2005}, {"title": "T\u00f4ky\u00f4 goddof\u00e2z\u00e2zu", "year": 2003}, {"title": "Serenity", "year": 2005}, {"title": "Walk the Line", "year": 2005}, {"title": "Ondskan", "year": 2003}, {"title": "The Notebook", "year": 2004}, {"title": "Diarios de motocicleta", "year": 2004}, {"title": "Lilja 4-ever", "year": 2002}, {"title": "Les triplettes de Belleville", "year": 2003}, {"title": "Gongdong gyeongbi guyeok JSA", "year": 2000}, {"title": "The Count of Monte Cristo", "year": 2002}, {"title": "Waking Life", "year": 2001}, {"title": "Remember the Titans", "year": 2000}, {"title": "Wo hu cang long", "year": 2000}, {"title": "Todo sobre mi madre", "year": 1999}, {"title": "Cast Away", "year": 2000}, 
    {"title": "The Boondock Saints", "year": 1999}, {"title": "The Insider", "year": 1999}, {"title": "October Sky", "year": 1999}, {"title": "Shrek", "year": 2001}, {"title": "Titanic", "year": 1997}, {"title": "Hana-bi", "year": 1997}, {"title": "Gattaca", "year": 1997}, {"title": "The Game", "year": 1997}, {"title": "Breaking the Waves", "year": 1996}, {"title": "Ed Wood", "year": 1994}, {"title": "What's Eating Gilbert Grape", "year": 1993}, {"title": "Tombstone", "year": 1993}, {"title": "The Sandlot", "year": 1993}, {"title": "The Remains of the Day", "year": 1993}, {"title": "Naked", "year": 1993}, {"title": "The Fugitive", "year": 1993}, {"title": "A Bronx Tale", "year": 1993}, {"title": "Batman: Mask of the Phantasm", "year": 1993}, {"title": "Lat sau san taam", "year": 1992}, {"title": "Night on Earth", "year": 1991}, {"title": "La double vie de V\u00e9ronique", "year": 1991}, {"title": "Boyz n the Hood", "year": 1991}, {"title": "Misery", "year": 1990}, {"title": "Awakenings", "year": 1990}, {"title": "Majo no takky\u00fbbin", "year": 1989}, {"title": "Glory", "year": 1989}, {"title": "Dip huet seung hung", "year": 1989}, {"title": "Back to the Future Part II", "year": 1989}, {"title": "Mississippi Burning", "year": 1988}, {"title": "Predator", "year": 1987}, {"title": "Evil Dead II", "year": 1987}, {"title": "Ferris Bueller's Day Off", "year": 1986}, {"title": "Down by Law", "year": 1986}, {"title": "The Goonies", "year": 1985}, {"title": "The Color Purple", "year": 1985}, {"title": "The Breakfast Club", "year": 1985}, {"title": "The Killing Fields", "year": 1984}, {"title": "Ghostbusters", "year": 1984}, {"title": "The Right Stuff", "year": 1983}, {"title": "The King of Comedy", "year": 1982}, {"title": "E.T. the Extra-Terrestrial", "year": 1982}, {"title": "Kramer vs. Kramer", "year": 1979}, {"title": "Days of Heaven", "year": 1978}, {"title": "The Outlaw Josey Wales", "year": 1976}, {"title": "The Man Who Would Be King", "year": 1975}, {"title": "The Conversation", "year": 1974}, {"title": "La plan\u00e8te sauvage", "year": 1973}, {"title": "The Day of the Jackal", "year": 1973}, {"title": "Badlands", "year": 1973}, {"title": "Cabaret", "year": 1972}, {"title": "Willy Wonka & the Chocolate Factory", "year": 1971}, {"title": "Midnight Cowboy", "year": 1969}, {"title": "Wait Until Dark", "year": 1967}, {"title": "Guess Who's Coming to Dinner", "year": 1967}, 
    {"title": "Bonnie and Clyde", "year": 1967}, {"title": "My Fair Lady", "year": 1964}, {"title": "Mary Poppins", "year": 1964}, {"title": "The Longest Day", "year": 1962}, {"title": "Jules et Jim", "year": 1962}, {"title": "The Innocents", "year": 1961}, {"title": "\u00c0 bout de souffle", "year": 1960}, {"title": "Red River", "year": 1948}, {"title": "Key Largo", "year": 1948}, {"title": "To Have and Have Not", "year": 1944}, {"title": "Shadow of a Doubt", "year": 1943}, {"title": "Stagecoach", "year": 1939}, {"title": "The Lady Vanishes", "year": 1938}, {"title": "Bringing Up Baby", "year": 1938}, {"title": "Bride of Frankenstein", "year": 1935}, {"title": "Duck Soup", "year": 1933}, {"title": "Scarface: The Shame of the Nation", "year": 1932}, {"title": "Frankenstein", "year": 1931}, {"title": "Roma", "year": 2018}, {"title": "God's Own Country", "year": 2017}, {"title": "Deadpool 2", "year": 2018}, {"title": "Wind River", "year": 2017}, {"title": "Get Out", "year": 2017}, {"title": "Mission: Impossible - Fallout", "year": 2018}, {"title": "En man som heter Ove", "year": 2015}, {"title": "What We Do in the Shadows", "year": 2014}, {"title": "Omoide no M\u00e2n\u00ee", "year": 2014}, {"title": "The Theory of Everything", "year": 2014}, {"title": "Kingsman: The Secret Service", "year": 2014}, {"title": "The Fault in Our Stars", "year": 2014}, {"title": "Me and Earl and the Dying Girl", "year": 2015}, {"title": "Birdman or (The Unexpected Virtue of Ignorance)", "year": 2014}, {"title": "La vie d'Ad\u00e8le", "year": 2013}, {"title": "Kai po che!", "year": 2013}, {"title": "The Broken Circle Breakdown", "year": 2012}, {"title": "Captain America: The Winter Soldier", "year": 2014}, {"title": "Rockstar", "year": 2011}, {"title": "Nebraska", "year": 2013}, {"title": "Wreck-It Ralph", "year": 2012}, {"title": "Le Petit Prince", "year": 2015}, {"title": "Detachment", "year": 2011}, {"title": "Midnight in Paris", "year": 2011}, {"title": "The Lego Movie", "year": 2014}, {"title": "Gravity", "year": 2013}, {"title": "Star Trek Into Darkness", "year": 2013}, {"title": "Beasts of No Nation", "year": 2015}, {"title": "The Social Network", "year": 2010}, {"title": "X: First Class", "year": 2011}, {"title": "The Hangover", "year": 2009}, {"title": "Skyfall", "year": 2012}, 
    {"title": "Silver Linings Playbook", "year": 2012}, {"title": "Argo", "year": 2012}, {"title": "(500) Days of Summer", "year": 2009}, {"title": "Harry Potter and the Deathly Hallows: Part 1", "year": 2010}, {"title": "Gake no ue no Ponyo", "year": 2008}, 
    {"title": "Frost/Nixon", "year": 2008}, {"title": "Papurika", "year": 2006}, {"title": "Changeling", "year": 2008}, {"title": "Flipped", "year": 2010}, {"title": "Toki o kakeru sh\u00f4jo", "year": 2006}, {"title": "Death Note: Desu n\u00f4to", "year": 2006}, {"title": "This Is England", "year": 2006}, {"title": "Ex Machina", "year": 2014}, {"title": "Efter brylluppet", "year": 2006}, {"title": "The Last King of Scotland", "year": 2006}, {"title": "Zodiac", "year": 2007}, {"title": "Lucky Number Slevin", "year": 2006}, {"title": "Joyeux No\u00ebl", "year": 2005}, {"title": "Control", "year": 2007}, {"title": "Tangled", "year": 2010}, {"title": "Zwartboek", "year": 2006}, {"title": "Brokeback Mountain", "year": 2005}, {"title": "3:10 to Yuma", "year": 2007}, {"title": "Crash", "year": 2004}, {"title": "Kung fu", "year": 2004}, {"title": "The Bourne Supremacy", "year": 2004}, {"title": "The Machinist", "year": 2004}, {"title": "Ray", "year": 2004}, {"title": "Lost in Translation", "year": 2003}, {"title": "Harry Potter and the Goblet of Fire", "year": 2005}, {"title": "Man on Fire", "year": 2004}, {"title": "Coraline", "year": 2009}, {"title": "The Last Samurai", "year": 2003}, {"title": "The Magdalene Sisters", "year": 2002}, {"title": "Good Bye Lenin!", "year": 2003}, {"title": "In America", "year": 2002}, {"title": "I Am Sam", "year": 2001}, {"title": "Adaptation.", "year": 2002}, {"title": "Black Hawk Down", "year": 2001}, {"title": "Road to Perdition", "year": 2002}, {"title": "Das Experiment", "year": 2001}, {"title": "Billy Elliot", "year": 2000}, {"title": "Hedwig and the Angry Inch", "year": 2001}, {"title": "Ocean's Eleven", "year": 2001}, {"title": "Vampire Hunter D: Bloodlust", "year": 2000}, {"title": "O Brother, Where Art Thou?", "year": 2000}, {"title": "Interstate 60: Episodes of the Road", "year": 2002}, {"title": "South Park: Bigger, Longer & Uncut", "year": 1999}, {"title": "Office Space", "year": 1999}, {"title": "Happiness", "year": 1998}, {"title": "Training Day", "year": 2001}, {"title": "Rushmore", "year": 1998}, {"title": "Abre los ojos", "year": 1997}, {"title": "Being John Malkovich", "year": 1999}, {"title": "As Good as It Gets", "year": 1997}, {"title": "The Fifth Element", "year": 1997}, {"title": "Le d\u00eener de cons", "year": 1998}, {"title": "Donnie Brasco", "year": 1997},
    {"title": "Shine", "year": 1996}, {"title": "Primal Fear", "year": 1996}, {"title": "Hamlet", "year": 1996}, {"title": "A Little Princess", "year": 1995}, {"title": "Do lok tin si", "year": 1995}, {"title": "Il postino", "year": 1994}, {"title": "Clerks", "year": 1994}, {"title": "Short Cuts", "year": 1993}, {"title": "Philadelphia", "year": 1993}, {"title": "The Muppet Christmas Carol", "year": 1992}, {"title": "Malcolm X", "year": 1992}, {"title": "The Last of the Mohicans", "year": 1992}, {"title": "Kurenai no buta", "year": 1992}, {"title": "Glengarry Glen Ross", "year": 1992}, {"title": "A Few Good Men", "year": 1992}, {"title": "Fried Green Tomatoes", "year": 1991}, {"title": "Barton Fink", "year": 1991}, 
    {"title": "Miller's Crossing", "year": 1990}, {"title": "Who Framed Roger Rabbit", "year": 1988}, {"title": "Spoorloos", "year": 1988}, {"title": "Withnail & I", "year": 1987}, {"title": "The Last Emperor", "year": 1987}, {"title": "Empire of the Sun", "year": 1987}, {"title": "Der Name der Rose", "year": 1986}, {"title": "Blue Velvet", "year": 1986}, {"title": "The Purple Rose of Cairo", "year": 1985}, {"title": "After Hours", "year": 1985}, {"title": "Zelig", "year": 1983}, {"title": "The Verdict", "year": 1982}, {"title": "Star Trek II: The Wrath of Khan", "year": 1982}, {"title": "First Blood", "year": 1982}, {"title": "Ordinary People", "year": 1980}, {"title": "Airplane!", "year": 1980}, {"title": "Rupan sansei: Kariosutoro no shiro", "year": 1979}, {"title": "Halloween", "year": 1978}, {"title": "Le locataire", "year": 1976}, {"title": "Love and Death", "year": 1975}, {"title": "The Taking of Pelham One Two Three", "year": 1974}, {"title": "Blazing Saddles", "year": 1974}, {"title": "Serpico", "year": 1973}, {"title": "Enter the Dragon", "year": 1973}, {"title": "Deliverance", "year": 1972}, {"title": "The French Connection", "year": 1971}, {"title": "Dirty Harry", "year": 1971}, {"title": "Where Eagles Dare", "year": 1968}, {"title": "The Odd Couple", "year": 1968}, {"title": "The Dirty Dozen", "year": 1967}, {"title": "Belle de jour", "year": 1967}, {"title": "A Man for All Seasons", "year": 1966}, {"title": "Repulsion", "year": 1965}, {"title": "Zulu", "year": 1964}, {"title": "Goldfinger", "year": 1964}, {"title": "The Birds", "year": 1963}, {"title": "Cape Fear", "year": 1962}, {"title": "Peeping Tom", "year": 1960}, {"title": "The Magnificent Seven", "year": 1960}, {"title": "Les yeux sans visage", "year": 1960}, {"title": "Invasion of the Body Snatchers", "year": 1956}, {"title": "Rebel Without a Cause", "year": 1955}, {"title": "The Ladykillers", "year": 1955}, {"title": "Sabrina", "year": 1954}, {"title": "The Quiet Man", "year": 1952}, {"title": "The Day the Earth Stood Still", "year": 1951}, {"title": "The African Queen", "year": 1951}, {"title": "Gilda", "year": 1946}, {"title": "Fantasia", "year": 1940}, {"title": "The Invisible Man", "year": 1933}, {"title": "Dark Waters", "year": 2019}, {"title": "Searching", "year": 2018}, {"title": "Once Upon a Time... in Hollywood", "year": 2019}, 
    {"title": "Nelyubov", "year": 2017}, {"title": "The Florida Project", "year": 2017}, {"title": "Just Mercy", "year": 2019}, {"title": "Gifted", "year": 2017}, {"title": "The Peanut Butter Falcon", "year": 2019}, {"title": "Victoria", "year": 2015}, {"title": "Mustang", "year": 2015}, {"title": "Guardians of the Galaxy Vol. 2", "year": 2017}, {"title": "Baby Driver", "year": 2017}, {"title": "Only the Brave", "year": 2017}, {"title": "Bridge of Spies", "year": 2015}, {"title": "Incredibles 2", "year": 2018}, {"title": "Moana", "year": 2016}, {"title": "Sicario", "year": 2015}, {"title": "Creed", "year": 2015}, {"title": "Leviafan", "year": 2014}, {"title": "Hell or High Water", "year": 2016}, {"title": "Philomena", "year": 2013}, {"title": "Dawn of the Planet of the Apes", "year": 2014}, {"title": "El cuerpo", "year": 2012}, {"title": "Serbuan maut", "year": 2011}, {"title": "End of Watch", "year": 2012}, {"title": "Kari-gurashi no Arietti", "year": 2010}, {"title": "A Star Is Born", "year": 2018}, {"title": "True Grit", "year": 2010}, {"title": "H\u00e6vnen", "year": 2010}, {"title": "Despicable Me", "year": 2010}, {"title": "50/50", "year": 2011}, {"title": "Kick-Ass", "year": 2010}, {"title": "Celda 211", "year": 2009}, {"title": "Moneyball", "year": 2011}, {"title": "La piel que habito", "year": 2011}, {"title": "Zombieland", "year": 2009}, {"title": "Die Welle", "year": 2008}, {"title": "Sherlock Holmes", "year": 2009}, {"title": "The Blind Side", "year": 2009}, {"title": "The Visitor", "year": 2007}, {"title": "Seven Pounds", "year": 2008}, {"title": "Eastern Promises", "year": 2007}, 
    {"title": "Stardust", "year": 2007}, {"title": "The Secret of Kells", "year": 2009}, {"title": "Inside Man", "year": 2006}, {"title": "Gone Baby Gone", "year": 2007}, {"title": "La Vie En Rose", "year": 2007}, {"title": "Huo Yuan Jia", "year": 2006}, {"title": "The Illusionist", "year": 2006}, {"title": "Dead Man's Shoes", "year": 2004}, {"title": "Harry Potter and the Half-Blood Prince", "year": 2009}, {"title": "300", "year": 2006}, {"title": "Match Point", "year": 2005}, {"title": "Watchmen", "year": 2009}, {"title": "Lord of War", "year": 2005}, {"title": "Saw", "year": 2004}, {"title": "Synecdoche, New York", "year": 2008}, {"title": "Mysterious Skin", "year": 2004}, {"title": "Jeux d'enfants", "year": 2003}, {"title": "Un long dimanche de fian\u00e7ailles", "year": 2004}, {"title": "The Station Agent", "year": 2003}, {"title": "21 Grams", "year": 2003}, {"title": "Boksuneun naui geot", "year": 2002}, {"title": "Finding Neverland", "year": 2004}, {"title": "25th Hour", "year": 2002}, {"title": "The Butterfly Effect", "year": 2004}, {"title": "28 Days Later...", "year": 2002}, {"title": "Batoru rowaiaru", "year": 2000}, {"title": "The Royal Tenenbaums", "year": 2001}, {"title": "Y tu mam\u00e1 tambi\u00e9n", "year": 2001}, {"title": "Harry Potter and the Sorcerer's Stone", "year": 2001}, {"title": "The Others", "year": 2001}, {"title": "Blow", "year": 2001}, {"title": "Enemy at the Gates", "year": 2001}, {"title": "Minority Report", "year": 2002}, {"title": "The Hurricane", "year": 1999}, {"title": "American Psycho", "year": 2000}, {"title": "Lola rennt", "year": 1998}, {"title": "The Thin Red Line", "year": 1998}, {"title": "Mulan", "year": 1998}, {"title": "Fear and Loathing in Las Vegas", "year": 1998}, {"title": "Funny Games", "year": 1997}, {"title": "Dark City", "year": 1998}, {"title": "Sleepers", "year": 1996}, {"title": "Lost Highway", "year": 1997}, {"title": "Sense and Sensibility", "year": 1995}, {"title": "Die Hard: With a Vengeance", "year": 1995}, {"title": "Dead Man", "year": 1995}, {"title": "The Bridges of Madison County", "year": 1995}, {"title": "Apollo 13", "year": 1995}, {"title": "Trois couleurs: Blanc", "year": 1994}, {"title": "Falling Down", "year": 1993}, {"title": "Dazed and Confused", "year": 1993}, {"title": "My Cousin Vinny", "year": 1992}, 
    {"title": "Omohide poro poro", "year": 1991}, {"title": "Delicatessen", "year": 1991}, {"title": "Home Alone", "year": 1990}, {"title": "The Godfather: Part III", "year": 1990}, {"title": "When Harry Met Sally...", "year": 1989}, {"title": "The Little Mermaid", "year": 1989}, {"title": "The Naked Gun: From the Files of Police Squad!", "year": 1988}, {"title": "Planes, Trains & Automobiles", "year": 1987}, {"title": "Lethal Weapon", "year": 1987}, {"title": "Blood Simple", "year": 1984}, {"title": "On Golden Pond", "year": 1981}, {"title": "Mad Max 2", "year": 1981}, {"title": "The Warriors", "year": 1979}, {"title": "The Muppet Movie", "year": 1979}, {"title": "Escape from Alcatraz", "year": 1979}, {"title": "Watership Down", "year": 1978}, {"title": "Midnight Express", "year": 1978}, {"title": "Close Encounters of the Third Kind", "year": 1977}, {"title": "The Long Goodbye", "year": 1973}, {"title": "Gi\u00f9 la testa", "year": 1971}, {"title": "Kelly's Heroes", "year": 1970}, {"title": "The Jungle Book", "year": 1967}, {"title": "Blowup", "year": 1966}, {"title": "A Hard Day's Night", "year": 1964}, {"title": "Breakfast at Tiffany's", "year": 1961}, {"title": "Giant", "year": 1956}, {"title": "From Here to Eternity", "year": 1953}, {"title": "Lifeboat", "year": 1944}, {"title": "The 39 Steps", "year": 1935}
];

export {movieDatabase};